# Generated by Django 4.2.3 on 2023-08-17 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dictonary', '0002_alter_word_options_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
